# hookの種類
#
# |   hookの名前   |            実行されるタイミング            |lazy OFF|lazy ON|
# |----------------|--------------------------------------------|--------|-------|
# |hook_add        |プラグインが dein.vim によって追加されたとき|OK      |OK     |
# |hook_source     |プラグインが読み込まれる直前                |NG      |OK     |
# |hook_post_source|プラグインが読み込まれた直後                |NG      |OK     |
# |hook_post_update|プラグインが更新された直後                  |OK      |OK     |
# |hook_done_update|プラグイン全ての更新が終わった直後          |OK      |OK     |
#
# 参考: https://qiita.com/delphinus/items/cd221a450fd23506e81a

# JSON
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

# Terraform
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']
hook_add = '''
let g:terraform_fmt_on_save = 1
'''

# Ruby
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'takkii/Bignyanco'

# Python
[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
hook_add = '''
autocmd BufWritePost *.py call Flake8()
autocmd FileType python map <buffer> <F3> :call Flake8()<CR> " キーバインド変更
let g:flake8_quickfix_height=7 " Quickfixの高さ
let g:flake8_show_in_gutter=1  " 左端にシンボルを表示
let g:flake8_show_in_file=1  " ファイル内にマークを表示
'''

# JSX syntax
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['typescriptreact']
hook_add = '''
let g:vim_jsx_pretty_colorful_config = 1
'''
